Repository OneLiteFeatherNET/AntiRedstoneClock-Remastered, pull requests merged in 2024-07, with the labels that each got.

#77 Fix tab completion for display command
  build.gradle.kts
  src/main/java/net/onelitefeather/antiredstoneclockremastered/AntiRedstoneClockRemastered.java
Labels: Bugfix

#78 Fix redstone clock flag for plotsquared
  PlotSquaredv7Support/src/main/java/net/onelitefeather/antiredstoneclockremastered/plotsquared/v7/PlotSquaredModernSupport.java
  PlotSquaredv7Support/src/main/java/net/onelitefeather/antiredstoneclockremastered/plotsquared/v7/RedstoneClockFlag.java
Labels: Bugfix

#79 1.21 Native Support
  PlotSquaredv4Support/build.gradle.kts
  PlotSquaredv4Support/src/main/java/net/onelitefeather/antiredstoneclockremastered/plotsquared/v4/PlotSquaredWhatTheHellSupport.java
  PlotSquaredv4Support/src/main/java/net/onelitefeather/antiredstoneclockremastered/plotsquared/v4/RedstoneClockFlag.java
  README.md
  build.gradle.kts
  settings.gradle.kts
  src/main/java/net/onelitefeather/antiredstoneclockremastered/AntiRedstoneClockRemastered.java
Labels: [PR] breaking changes, Feature

#80 Dontation information
  build.gradle.kts
  src/main/java/net/onelitefeather/antiredstoneclockremastered/AntiRedstoneClockRemastered.java
  src/main/java/net/onelitefeather/antiredstoneclockremastered/listener/PlayerListener.java
  src/main/java/net/onelitefeather/antiredstoneclockremastered/utils/Constants.java
  src/main/resources/antiredstoneclockremasterd_en_US.properties
Labels: Feature

#81 Implement Update Service
  build.gradle.kts
  settings.gradle.kts
  src/main/java/net/onelitefeather/antiredstoneclockremastered/AntiRedstoneClockRemastered.java
  src/main/java/net/onelitefeather/antiredstoneclockremastered/listener/PlayerListener.java
  src/main/java/net/onelitefeather/antiredstoneclockremastered/service/UpdateService.java
  src/main/java/net/onelitefeather/antiredstoneclockremastered/utils/Constants.java
  src/main/resources/antiredstoneclockremasterd_en_US.properties
Labels: Feature

#84 Fix argument order for translation
  src/main/java/net/onelitefeather/antiredstoneclockremastered/commands/DisplayActiveClocksCommand.java
  src/main/resources/antiredstoneclockremasterd.properties
Labels: Bugfix

#86 Fix NullPointerExcpetion for Updater when the players join
  src/main/java/net/onelitefeather/antiredstoneclockremastered/service/UpdateService.java
Labels: good first issue, [PR] bugfix, Bugfix
